apiVersion: v1
kind: Secret
metadata:
  name: gpu-telemetry-secret
  namespace: {{ .Values.namespace | default "gpu-telemetry" }}
type: Opaque
stringData:
  INFLUXDB_TOKEN: {{ .Values.influxdb.secret.token | quote }}
  INFLUXDB_PASSWORD: {{ .Values.influxdb.secret.password | quote }}
