apiVersion: v2
name: gpu-telemetry-pipeline
description: A Helm chart for deploying the GPU Telemetry Pipeline on Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - gpu
  - telemetry
  - monitoring
  - message-queue
  - dcgm
maintainers:
  - name: Cisco
    email: support@example.com
